spring.application.name=processdocument
server.port=8080

# Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/document_qa_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Enable Async
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10

# AI Service URL
ai.service.url=http://localhost:8000

# JWT Secret Key - IMPORTANT: Generate a secure random key for production
# You can use an online generator to create a 256-bit key
application.security.jwt.secret-key=7575dac6117a39069294ed2a8f7aa98b456c37346098a6f78d82c497a5ec0a38
application.security.jwt.expiration=86400000